/** Стили элипсов фона */
export const ElipsesClassNames = {
  rightTop: [
    "ellips",
    "absolute",
    "w-half-screen",
    "h-half-screen",
    "top-0",
    "right-0",
    "bg-elips-green",
    "opacity-15",
    "blur-6.25",
    "rotate-minus131",
  ].join(" "),
  leftTop: [
    "ellips",
    "absolute",
    "w-half-screen",
    "h--half-screen",
    "top-0",
    "left-0",
    "bg-light-green",
    "opacity-50",
    "blur-6.25",
    "rotate-minus65.41",
  ].join(" "),
  leftBottom: [
    "ellips",
    "absolute",
    "w-half-screen",
    "h-half-screen",
    "bottom-0",
    "left-0",
    "bg-elips-green",
    "opacity-15",
    "blur-6.25",
    "rotate-minus65.41",
  ].join(" "),
  rightBottom: [
    "ellips",
    "absolute",
    "w-half-screen",
    "h-half-screen",
    "bottom-0",
    "right-0",
    "bg-light-green",
    "opacity-50",
    "blur-6.25",
    "rotate-minus131",
  ].join(" "),
};
