/** Стили элипсов фона */
export const ElipsesClassNames = {
  rightTop: [
    "ellips",
    "absolute",
    "w-[50vw]",
    "h-[50vh]",
    "top-0",
    "right-0",
    "bg-[#3AC922]",
    "opacity-[0.15]",
    "blur-[6.25rem]",
    "rotate-[-131deg]",
  ].join(" "),
  leftTop: [
    "ellips",
    "absolute",
    "w-[50vw]",
    "h-[50vh]",
    "top-0",
    "left-0",
    "bg-[#B2F1DE]",
    "opacity-50",
    "blur-[6.25rem]",
    "rotate-[-65.41deg]",
  ].join(" "),
  leftBottom: [
    "ellips",
    "absolute",
    "w-[50vw]",
    "h-[50vh]",
    "bottom-0",
    "left-0",
    "bg-[#3AC922]",
    "opacity-[0.15]",
    "blur-[6.25rem]",
    "rotate-[-65.41deg]",
  ].join(" "),
  rightBottom: [
    "ellips",
    "absolute",
    "w-[50vw]",
    "h-[50vh]",
    "bottom-0",
    "right-0",
    "bg-[#B2F1DE]",
    "opacity-50",
    "blur-[6.25rem]",
    "rotate-[-131deg]",
  ].join(" "),
};
